name: deploy_to_firebase_hosting

on:
  push:
    branches:
      - master

jobs:
  deploy_to_firebase_hosting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@master

      - name: Deploy to Firebase
        uses: rey0811/introduction@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
